package it.polimi.ingsw.server.model.game;

public enum GameStatusEnum {
    WAITING,
    STARTING,
    ASSIGNING_STARTER_CARDS,
    CHOOSING_COLOR,
    DRAWING_FIRST_CARDS,
    ASSIGNING_COMMON_OBJECTIVES,
    CHOOSING_PERSONAL_OBJECTIVE,
    ASSIGNING_FIRST_PLAYER,
    PLAYING,
    ENDING,
    ERROR
}
